joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ur5e_shoulder_pan_joint
    - ur5e_shoulder_lift_joint
    - ur5e_elbow_joint
    - ur5e_wrist_1_joint
    - ur5e_wrist_2_joint
    - ur5e_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5e_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_elbow_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint