<?xml version="1.0" ?>
<robot name="mir200_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_diameter" value="0.125"/>

    <link name="base_footprint"/>
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mir200_robot_description/meshes/mir200_base.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mir200_robot_description/meshes/mir200_base.dae" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
        </inertial>
    </link>

    <joint name="base_footprint_fixed" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="insert_wheel" params="prefix direction">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://mir200_robot_description/meshes/mir200_wheel.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://mir200_robot_description/meshes/mir200_wheel.dae" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.5"/>
                <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0003"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:insert_wheel prefix="l" direction="1"/>
</robot>