# Odometry Model Parameters
odom_model_type: diff
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.8
odom_alpha4: 0.2
odom_alpha5: 0.1
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map

# Laser Model Parameters
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_lambda_short: 0.1
laser_model_type: likelihood_field
laser_likelihood_max_dist: 2.0

# Filter related Parameters
min_particles: 500
max_particles: 5000
kld_err: 0.05
kld_z: 0.99
transform_tolerance: 0.2
laser_max_beams: 30
update_min_d: 0.2
update_min_a: 0.5
resample_interval: 1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# Initial Position
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.5
initial_cov_yy: 0.5
initial_cov_aa: 0.1

# For Debug
gui_publish_rate: 10