# 2D Costmap parameters
# Coordinate frame and tf parameters
global_frame: map
robot_base_frame: base_footprint
transform_tolerance: 1.0

# Rate parameters
update_frequency: 10.0
publish_frequency: 5.0
max_obstacle_height: 2.0
obstacle_range: 2.0
raytrace_range: 3.0
cost_scaling_factor: 10.0

# Robot description parameters
inflation_radius: 0.4
# robot_radius: 0.20
footprint: [ [0.470, -0.300], [-0.400, -0.300], [-0.400, 0.300], [0.470, 0.300] ]

observation_sources: laser_scan_sensor
laser_scan_sensor: {
  topic: scan,
  sensor_frame: base_link,
  observation_persistence: 0.0,
  expected_update_rate: 0.5,
  data_type: LaserScan,
  clearing: true,
  marking: true,
  max_obstacle_height: 2.0,
  min_obstacle_height: 0.0,
  obstacle_range: 2.5,
  raytrace_range: 3.0
}

# Map management parameters ###
static_map: true
rolling_window: false
unknown_cost_value:  0
publish_voxel_map: false
lethal_cost_threshold: 100
map_topic: map

# Map type parameters
map_type: costmap
track_unknown_space: false