<?xml version="1.0" ?>
<robot name="mir200_w_ur5e_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- include other files -->
    <xacro:include filename="$(find mir200_w_ur5e_robot_description)/urdf/gazebo.urdf.xacro" />
    <xacro:include filename="$(find mir200_w_ur5e_robot_description)/urdf/inertial_macro.xacro" />

    <!-- robot specifications -->
    <xacro:property name="wheel_diameter" value="0.125"/>
    <xacro:property name="wheel_seperation" value="0.438"/>
    <xacro:property name="caster_wheel_seperation" value="0.410"/>

    <xacro:property name="robot_weight" value="65.0"/>
    <xacro:property name="robot_length" value="0.890"/>
    <xacro:property name="robot_width" value="0.580"/>
    <xacro:property name="robot_height" value="0.305"/>


    <!-- URDF -->
    <link name="base_footprint"/>
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_base.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_base.dae" scale="1 1 1"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${robot_weight}"/>
            <origin xyz="0 0 0.150" rpy="0 0 0"/>
            <xacro:box_inertia m="${robot_weight}" x="${robot_length}" y="${robot_width}" z="${robot_height}"/>
        </inertial>
    </link>

    <joint name="base_footprint_fixed" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="insert_wheel" params="prefix direction">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${direction*pi/2}"/>
                <geometry>
                    <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_wheel.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${direction*pi/2}"/>
                <geometry>
                    <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_wheel.dae" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <mass value="1.0"/>
                <xacro:cylinder_inertia m="1.0" r="0.0625" h="0.0345"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${direction*wheel_seperation/2} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="insert_front_caster_wheel" params="prefix direction">
        <link name="${prefix}_front_caster_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_front_caster_wheel.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_front_caster_wheel.dae" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="1.0"/>
                <xacro:cylinder_inertia m="1.0" r="0.0625" h="0.032"/>
            </inertial>
        </link>

        <joint name="${prefix}_front_caster_wheel_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_front_caster_wheel"/>
            <origin xyz="0.3 ${direction*caster_wheel_seperation/2} 0.001" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="insert_rear_caster_wheel" params="prefix direction">
        <link name="${prefix}_rear_caster_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_rear_caster_wheel.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://mir200_w_ur5e_robot_description/meshes/mir200_rear_caster_wheel.dae" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="1.0"/>
                <xacro:cylinder_inertia m="1.0" r="0.0625" h="0.032"/>
            </inertial>
        </link>

        <joint name="${prefix}_rear_caster_wheel_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_rear_caster_wheel"/>
            <origin xyz="-0.3 ${direction*caster_wheel_seperation/2} 0.001" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:insert_wheel prefix="l" direction="1"/>
    <xacro:insert_wheel prefix="r" direction="-1"/>

    <xacro:insert_front_caster_wheel prefix="l" direction="1"/>
    <xacro:insert_front_caster_wheel prefix="r" direction="-1"/>

    <xacro:insert_rear_caster_wheel prefix="l" direction="1"/>
    <xacro:insert_rear_caster_wheel prefix="r" direction="-1"/>

    <link name="front_lidar">
        <visual>
            <origin xyz="0 0 0.012" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
            <material name="dark_gray">
                <color rgba="0.3 0.3 0.3"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0.012" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.5"/>
            <xacro:cylinder_inertia m="0.5" r="0.005" h="0.1"/>
        </inertial>
    </link>

    <joint name="front_lidar_fixed" type="fixed">
        <parent link="base_link"/>
        <child link="front_lidar"/>
        <origin xyz="0.426 0.235 0.13" rpy="0 0 0"/>
    </joint>

    <link name="rear_lidar">
        <visual>
            <origin xyz="0 0 0.012" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
            <material name="dark_gray">
                <color rgba="0.3 0.3 0.3"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0.012" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.5"/>
            <xacro:cylinder_inertia m="0.5" r="0.005" h="0.1"/>
        </inertial>
    </link>

    <joint name="rear_lidar_fixed" type="fixed">
        <parent link="base_link"/>
        <child link="rear_lidar"/>
        <origin xyz="-0.360 -0.235 0.13" rpy="0 0 ${pi}"/>
    </joint>
</robot>