# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - l_bogie_suspension_joint
    - l_rear_caster_rotate_joint
    - l_rear_caster_wheel_joint
    - l_wheel_joint
    - l_front_caster_rotate_joint
    - l_front_caster_wheel_joint
    - ur5e_shoulder_pan_joint
    - ur5e_shoulder_lift_joint
    - ur5e_elbow_joint
    - ur5e_wrist_1_joint
    - ur5e_wrist_2_joint
    - ur5e_wrist_3_joint
    - finger_joint
    - r_bogie_suspension_joint
    - r_rear_caster_rotate_joint
    - r_rear_caster_wheel_joint
    - r_wheel_joint
    - r_front_caster_rotate_joint
    - r_front_caster_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint